### ISSUE TITLE
LSPが効かない

### ISSUE THREAD

**Issue by po3rin** [po3rin/dotfiles#1]
## Vimのバージョン

```
$ vim -h
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 29 2020 01:33:22)
```

## 状況と問題

vim-lsp-settingsだけではLSPの全ての機能が動かない。例えば```:LspDefinition```を実行すると下記のようなエラーになる。

<img width="533" alt="スクリーンショット 2020-07-02 22 41 51" src="https://user-images.githubusercontent.com/29445112/86366062-4cb11e80-bcb5-11ea-9f10-2c9104b1d4d8.png">

```
# error message
Retrieving definition not supported for go
```

言語ごとに設定を書くと助長なのでvim-lsp-settingsでの管理に移したい。

## 踏んだ手順

* vim-goの削除
* 下記プラグインのインストール
```
" LSP
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
```

* 下記設定の追加
https://github.com/po3rin/dotfiles/blob/master/.vimrc#L167-L202

* 必要な依存のインストール実行

Goファイルを開いてる時に

```
:LspInstallServer
```

インストールされる依存は下記

```
go: downloading golang.org/x/tools v0.0.0-20200702044944-0cc1aa72b347
go: downloading golang.org/x/tools/gopls v0.4.2
go: golang.org/x/tools/gopls latest => v0.4.2
go: downloading golang.org/x/tools v0.0.0-20200701133321-6ddc6be4d35f
go: downloading honnef.co/go/tools v0.0.1-2020.1.4
go: downloading mvdan.cc/xurls/v2 v2.2.0
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: downloading golang.org/x/mod v0.2.0
go: downloading github.com/BurntSushi/toml v0.3.1
```

## 対象の.vimrc
https://github.com/po3rin/dotfiles/blob/master/.vimrc

## 参考
「Vim をモダンな IDE に変える LSP の設定」
https://mattn.kaoriya.net/software/vim/20191231213507.html

「vim-goからvim-lspへ移行しました」
https://christina04.hatenablog.com/entry/migrate-from-vim-go-to-vim-lsp

**Comment by skanehira** [comment]
# 補足

1. `Plug 'prabirshrestha/async.vim'` は`vim-lsp`に統合されたので、不要になりました
2. `vim-lsp-settings` は lsp の設定とインストールを補助してくれるプラグインなのでlspを使いたいなら`vim-lsp`が必要です（なのでエラーは`vim-lsp-settings`とは関係ない可能性が高い）

# 確認してほしいこと
1. Vimを go.mod があるディレクトリで起動したかどうか
2. GO111MODULEの設定値はどうなっているか
3. GoのプロジェクトはGOPATH配下なのかどうか
4. `vim-lsp`のログがどうなっているか(折り畳める状態でコメントに貼って頂ければ)

**Comment by po3rin** [comment]
ありがとうございます。とりあえず```prabirshrestha/async.vim```を削除しました。
vim-lspはすでに```prabirshrestha/vim-lsp```をインストールしています。

確認事項
1. go.modのあるディレクトリで起動しています。
2. GO111MODULE=onになっています。
3. GOPATH配下ではありません。
4. 下記vim-lsp.logの内容です。何個か関数(LspDefinitionやLspHoverなど)を実行したのですがエラーが出ない😱😱

vim-lsp.log
```
 21 金  7/ 3 00:14:29 2020:["lsp#register_server","server registered","gopls"]
 20 金  7/ 3 00:14:30 2020:["vim-lsp signs enabled"]
 19 金  7/ 3 00:14:30 2020:["vim-lsp highlighting enabled (textprop)"]
 18 金  7/ 3 00:14:30 2020:["s:on_text_document_did_open()",1,"go","/Users/hiromunakamura/hi_dev/chrbmfzf","file:///Users/hir    omunakamura/hi_dev/chrbmfzf/main.go"]
 17 金  7/ 3 00:14:38 2020:["s:on_text_document_did_change()",1]
 16 金  7/ 3 00:14:38 2020:["s:send_didchange_queue() will be triggered"]
 15 金  7/ 3 00:14:41 2020:["s:on_text_document_did_change()",1]
 14 金  7/ 3 00:14:42 2020:["s:send_event_queue()"]
 13 金  7/ 3 00:15:03 2020:["s:on_text_document_did_save()",1]
 12 金  7/ 3 00:15:03 2020:["s:on_text_document_did_close()",1]
 11 金  7/ 3 00:15:26 2020:["vim-lsp signs enabled"]
 10 金  7/ 3 00:15:26 2020:["vim-lsp highlighting enabled (textprop)"]
  9 金  7/ 3 00:15:26 2020:["s:on_text_document_did_open()",1,"","/Users/hiromunakamura","file:///Users/hiromunakamura/asynco    mplete.log"]
  8 金  7/ 3 00:15:36 2020:["s:on_text_document_did_close()",1]
  7 金  7/ 3 00:15:40 2020:["vim-lsp signs enabled"]
  6 金  7/ 3 00:15:40 2020:["vim-lsp highlighting enabled (textprop)"]
  5 金  7/ 3 00:15:40 2020:["s:on_text_document_did_open()",1,"","/Users/hiromunakamura","file:///Users/hiromunakamura/vim-ls    p.log"]
```

ちなみにGoのバージョンは1.14.3です。

```
$ go version
go version go1.14.3 darwin/amd64
```

vim周りのdebug力が皆無ですいません。。

**Comment by budougumi0617** [comment]
vimrcは問題なさそう。 `go get -u golang.org/x/tools/gopls` して最新のgoplsを取ってくるとか…？ 🤔 
```
vim -h
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 19 2020 22:07:34)
```

私のMac上で
```
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```
したあと、

https://github.com/po3rin/dotfiles/blob/master/.vimrc
をホームディレクトリに置いて `:PlugInstall` したあとGoのファイルいじったらこんな感じで動きました（ `:LspDefinition` も）
<img width="536" alt="スクリーンショット 2020-07-03 0 34 12" src="https://user-images.githubusercontent.com/1883265/86378756-f946cc80-bcc4-11ea-87fd-d758fafd9a0c.png">
// GOPATH外のディレクトリで確認

**Comment by po3rin** [comment]
うわー@budougumi0617さんまで！こんな時間に申し訳ないです。。
@budougumi0617 さんの環境で動いたのであれば僕の何かしらの環境ですね。。

なぜかvim-lsp-settingを無視して下記を入れると動くんですよね。。。

```
if executable('gopls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': {server_info->['gopls']},
        \ 'whitelist': ['go'],
        \ })
    autocmd BufWritePre *.go LspDocumentFormatSync
endif
```

**Comment by budougumi0617** [comment]
諸事情で最近3時まで起きているので…ｗ
それぞれのpluginは最新になっているんですよね？
blmに関連して最近関数名が変わってますね。それが噛み合っていないとか？

https://github.com/prabirshrestha/vim-lsp/pull/847
https://github.com/mattn/vim-lsp-settings/issues/266

**Comment by po3rin** [comment]
あーーpluginをアップデートしたら動きました！！！！過去にvim-lspを興味で入れてそのまま放置していたのを忘れていました！！！！恥ずかしい。。

@budougumi0617 @skanehira さん本当にありがとうございます！！🙇‍♂️🙇‍♂️
